config/routes.rb
Rails.application.routes.draw do
  # resources :articles
  resources :blog_apps
  resources :comics
  # get 'blog_apps'
  get 'comics' => 'comics#index', as: 'comic_home'
  get 'comics/new' => 'comics#new', as: 'comic_new'
  post 'comics/create' => 'comics#create', as: 'create_comic'
  get 'comics/:id/edit', to: 'comics#edit', as: 'comic_edit'
  get 'comics/:id' => 'comics#show', as: 'comic_show'
  patch 'comics/:id', to: 'comics#update'
  get 'home/index'
  # get '/comics' => 'comics#index'
  # get '/comics' => 'comics#new', as 'new_comic'
  # post '/comics' => 'comics#create', as 'create_comic'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "index#index"
  # root "blog_apps#index"
  # root "comics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :name, :body, presence:true
end

app/models/blog_app.rb
class BlogApp < ApplicationRecord
  validates :title, :name, :about, presence: true
end

app/models/comic.rb
class Comic < ApplicationRecord
  validates :name, presence: true
  validates :body, presence: true, length: {maximum: 100}
  

  def self.search(search)
    if search
      name = Comic.find_by(name: search)
      if name
        self.where(name: search)
      else
        @comics = Comic.all
      end
    else
      @comics = Comic.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: 'vic', password: 'vic', only: [:create, :update, :destroy]
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
end

app/controllers/blog_apps_controller.rb
class BlogAppsController < ApplicationController
  before_action :set_blog_app, only: %i[ show edit update destroy ]

  # GET /blog_apps or /blog_apps.json
  def index
    @blog_apps = BlogApp.all
  end

  # GET /blog_apps/1 or /blog_apps/1.json
  def show
  end

  # GET /blog_apps/new
  def new
    @blog_app = BlogApp.new
  end

  # GET /blog_apps/1/edit
  def edit
  end

  # POST /blog_apps or /blog_apps.json
  def create
    @blog_app = BlogApp.new(blog_app_params)

    respond_to do |format|
      if @blog_app.save
        format.html { redirect_to blog_app_url(@blog_app), notice: "Blog app was successfully created." }
        format.json { render :show, status: :created, location: @blog_app }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_apps/1 or /blog_apps/1.json
  def update
    respond_to do |format|
      if @blog_app.update(blog_app_params)
        format.html { redirect_to blog_app_url(@blog_app), notice: "Blog app was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_app }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_apps/1 or /blog_apps/1.json
  def destroy
    @blog_app.destroy

    respond_to do |format|
      format.html { redirect_to blog_apps_url, notice: "Blog app was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_app
      @blog_app = BlogApp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_app_params
      params.require(:blog_app).permit(:title, :name, :about)
    end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  def index
    @comic = Comic.search(params[:search])
  end

  def show
    @comic = Comic.find(params[:id])
    render :show
  end

  def new
    @comic = Comic.new
  end

  def create
    @comic = Comic.new(comic_params)

    if @comic.save
      redirect_to comic_home_path
    else
      render :new
    end
  end

  def edit
    @comic = Comic.find(params[:id])
    render :edit
  end

  def update
    @comic = Comic.find(params[:id])

    if @comic.update(params.require(:comic).permit(:name, :body))
      flash[:success] = "Comic item successfully updated!"
      redirect_to comics_path(@comic)
    else
      flash.now[:error] = "Comic item update failed"
      render :edit
    end
  end

  def destroy
    @comic = Comic.find(params[:id])
    if @comic.present?
      @comic.destroy
    end
    redirect_to comic_home_path(@comic)
end

  private

  def comic_params
    params.require(:comic).permit(:name, :body, :search)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/blog_apps_helper.rb
module BlogAppsHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog_apps/_blog_app.html.erb
<div id="<%= dom_id blog_app %>">
  <p>
    <strong>Title:</strong>
    <%= blog_app.title %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= blog_app.name %>
  </p>

  <p>
    <strong>About:</strong>
    <%= blog_app.about %>
  </p>

</div>

app/views/blog_apps/_form.html.erb
<%= form_with(model: blog_app) do |form| %>
  <% if blog_app.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog_app.errors.count, "error") %> prohibited this blog_app from being saved:</h2>

      <ul>
        <% blog_app.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :about, style: "display: block" %>
    <%= form.text_field :about %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_apps/edit.html.erb
<h1>Editing blog app</h1>

<%= render "form", blog_app: @blog_app %>

<br>

<div>
  <%= link_to "Show this blog app", @blog_app %> |
  <%= link_to "Back to blog apps", blog_apps_path %>
</div>

app/views/blog_apps/index.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <img class="blog-img" src="<%= image_path 'cloud' %>"
</div>
<h1 class="title">Blog apps</h1>


<div id="blog_apps">
  <% @blog_apps.each do |blog_app| %>
    <%= render blog_app %>
    <p>
      <%= link_to "Show this blog app", blog_app %>
    </p>
  <% end %>
</div>

<%= link_to "New blog app", new_blog_app_path %>

app/views/blog_apps/new.html.erb
<h1>New blog app</h1>

<%= render "form", blog_app: @blog_app %>

<br>

<div>
  <%= link_to "Back to blog apps", blog_apps_path %>
</div>

app/views/blog_apps/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog_app %>

<div>
  <%= link_to "Edit this blog app", edit_blog_app_path(@blog_app) %> |
  <%= link_to "Back to blog apps", blog_apps_path %>

  <%= button_to "Destroy this blog app", @blog_app, method: :delete %>
</div>

app/views/comics/_comic.html.erb
<div id="<%= dom_id comic %>">
  <p>
    <strong>Name:</strong>
    <%= comic.name %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= comic.body %>
  </p>
</div>

app/views/comics/_form.html.erb
<%= form_with(model: comic) do |form| %>
  <% if comic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
        <% comic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comics/create.html.erb
<h1>Comics#create</h1>
<p>Find me in app/views/comics/create.html.erb</p>

app/views/comics/edit.html.erb
<div class="edit-container">
<h1>Editing Comic</h1>

<%= render "form", comic: @comic %>

<br>

<div class="edit-btn">
  <%= link_to "Show this comic", @comic %> |
  <%= link_to "Back to comics", comics_path %>
</div>
<div>

app/views/comics/index.html.erb
<div  class="comics">

  <div class="backdrop"></div>
  <div class="overlay"></div>
  <div class="comics-header-container">
    <h1 class="comics-header">National <span>Vic Store</span></h1>
  </div>

  <table class="comics-table">
    <% @comic.each do |comic| %>
    <tbody class="table-body">
      <tr class="table-row-content">
        <td class="table-row-flex">
          <div class="table-row-div table-row-id">
            <p>ISSUE #</p>
            <p class"table-body-id"><%= comic.id %>   </p>
          </div>
          <div class="table-row-div table-row-name">
            <p><%= comic.name %> </p>
          </div>
          <div class="table-row-div table-row-body">
            <p class="table-body-body"><%= comic.body %> </p>
          </div>
        </td>
      </tr>
      <tr class="table-row-btn">
        <td class="eye"><%= link_to image_tag('eye.png', alt: "eye logo"), comic_show_path(comic) %></td> 
        <td class="reset"><%= link_to image_tag('reset.png', alt: "eye logo"), comic_edit_path(comic)  %> </td> 
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="search-bar">
    <div class="search-bar-btn">
      <h1>Comic</h1>
      <%= link_to 'Home', comic_home_path %>
      <%= link_to 'Create', comic_new_path %>
    </div>
    <%= form_tag(comics_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag ("Search") %>
    <% end %>
 </div>

  <div class="loader-container">
    <img class="comic-loader" src="<%= image_path 'loader' %>"
  </div>
  
</div>

app/views/comics/new.html.erb
<h1> NEW COMIC</h1>



<%= form_with scope: :comic, url: create_comic_path, local: true do |f| %>
  
  <p>
    <% if @comic.errors.any? %>
      <ul>
        <% @comic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

    <% end %>

  </p>

  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  
  
  <p>
    <%= f.label :body %><br/>
    <%= f.text_field :body %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>


<div>
  <%= link_to "Back to Comics", comics_path %>
</div>

 

app/views/comics/show.html.erb
<h1>Show comic</h1>

<%= render @comic %>

<div class="show-btn">
  <%= link_to "Edit this comic", comic_edit_path  %> 
  <%= link_to "Back to comics", comics_path %>

  
  <%= button_to "Destroy this blog app", @blog_app, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "My Blog", posts_path %>
<p>Find me in app/views/vic/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>National Vic Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alexandria&family=Bangers&family=Mr+Dafoe&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>

app/views/vics/_form.html.erb
<%= form_with(model: vic) do |form| %>
  <% if vic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vic.errors.count, "error") %> prohibited this vic from being saved:</h2>

      <ul>
        <% vic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :about, style: "display: block" %>
    <%= form.text_field :about %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vics/_vic.html.erb
<div id="<%= dom_id vic %>">
  <p>
    <strong>Title:</strong>
    <%= vic.title %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= vic.name %>
  </p>

  <p>
    <strong>About:</strong>
    <%= vic.about %>
  </p>

</div>